package elementicraft.client;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

// Date: 24/07/2016 22:58:02
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX



import net.minecraft.entity.Entity;
import net.minecraft.entity.SharedMonsterAttributes;
import net.minecraft.entity.ai.EntityAIAttackMelee;
import net.minecraft.entity.ai.EntityAIHurtByTarget;
import net.minecraft.entity.ai.EntityAILookIdle;
import net.minecraft.entity.ai.EntityAIMoveTowardsRestriction;
import net.minecraft.entity.ai.EntityAINearestAttackableTarget;
import net.minecraft.entity.ai.EntityAIPanic;
import net.minecraft.entity.ai.EntityAISwimming;
import net.minecraft.entity.ai.EntityAIWatchClosest;
import net.minecraft.entity.monster.EntityMob;
import net.minecraft.entity.passive.EntityCow;
import net.minecraft.entity.passive.EntityPig;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.Item;
import net.minecraft.world.World;








public class fire_elemental extends ModelBase
{
  //fields
    ModelRenderer Shape9;
    ModelRenderer rightarm;
    ModelRenderer Shape8;
    ModelRenderer rightarm2;
    ModelRenderer Shape7;
    ModelRenderer leftarm;
    ModelRenderer Shape6;
    ModelRenderer leftarm2;
    ModelRenderer Shape5;
    ModelRenderer body;
    ModelRenderer Shape4;
    ModelRenderer body2;
    ModelRenderer Shape3;
    ModelRenderer head;
    ModelRenderer Shape2;
    ModelRenderer head2;
    ModelRenderer Shape1;
    ModelRenderer head3;
    ModelRenderer head4;
    ModelRenderer eyes;
  
  public fire_elemental()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Shape9 = new ModelRenderer(this, 59, 7);
      Shape9.addBox(0F, 0F, 0F, 1, 3, 1);
      Shape9.setRotationPoint(-3F, 5F, -2F);
      Shape9.setTextureSize(64, 32);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 40, 16);
      rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
      rightarm.setRotationPoint(-5F, -6F, 0F);
      rightarm.setTextureSize(64, 32);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0.3490659F);
      Shape8 = new ModelRenderer(this, 59, 0);
      Shape8.addBox(0F, 0F, 0F, 1, 5, 1);
      Shape8.setRotationPoint(-1F, 6F, 0F);
      Shape8.setTextureSize(64, 32);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      rightarm2 = new ModelRenderer(this, 57, 16);
      rightarm2.addBox(0F, 0F, -1F, 1, 12, 2);
      rightarm2.setRotationPoint(-7F, -10F, 0F);
      rightarm2.setTextureSize(64, 32);
      rightarm2.mirror = true;
      setRotation(rightarm2, 0F, 0F, 0.3490659F);
      Shape7 = new ModelRenderer(this, 59, 7);
      Shape7.addBox(0F, 0F, 0F, 1, 3, 1);
      Shape7.setRotationPoint(0F, 12.33333F, 0F);
      Shape7.setTextureSize(64, 32);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      leftarm = new ModelRenderer(this, 40, 16);
      leftarm.addBox(-1F, -2F, -2F, 4, 12, 4);
      leftarm.setRotationPoint(5F, -6F, 0F);
      leftarm.setTextureSize(64, 32);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, -0.3490659F);
      Shape6 = new ModelRenderer(this, 59, 0);
      Shape6.addBox(0F, 0F, 0F, 1, 5, 1);
      Shape6.setRotationPoint(-2F, 17F, 0F);
      Shape6.setTextureSize(64, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      leftarm2 = new ModelRenderer(this, 57, 16);
      leftarm2.addBox(0F, 0F, -1F, 1, 12, 2);
      leftarm2.setRotationPoint(6F, -10F, 0F);
      leftarm2.setTextureSize(64, 32);
      leftarm2.mirror = true;
      setRotation(leftarm2, 0F, 0F, -0.3490659F);
      Shape5 = new ModelRenderer(this, 59, 0);
      Shape5.addBox(0F, 0F, 0F, 1, 5, 1);
      Shape5.setRotationPoint(2F, 14F, -2F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      body = new ModelRenderer(this, 16, 16);
      body.addBox(-4F, 0F, -2F, 8, 12, 4);
      body.setRotationPoint(0F, -8F, 0F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 59, 7);
      Shape4.addBox(0F, 0F, 0F, 1, 3, 1);
      Shape4.setRotationPoint(-2F, 10F, 2F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      body2 = new ModelRenderer(this, 16, 20);
      body2.addBox(0F, 0F, 0F, 6, 9, 1);
      body2.setRotationPoint(-3F, -7F, -3F);
      body2.setTextureSize(64, 32);
      body2.mirror = true;
      setRotation(body2, 0.1183519F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 59, 7);
      Shape3.addBox(0F, 0F, 0F, 1, 3, 1);
      Shape3.setRotationPoint(2F, 9F, -1F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, -8F, 0F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0.1396263F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 59, 0);
      Shape2.addBox(0F, 0F, 0F, 1, 5, 1);
      Shape2.setRotationPoint(4F, 8F, 3F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      head2 = new ModelRenderer(this, 33, 8);
      head2.addBox(0F, 0F, 0F, 6, 6, 2);
      head2.setRotationPoint(-3F, -16F, 2F);
      head2.setTextureSize(64, 32);
      head2.mirror = true;
      setRotation(head2, -0.2094395F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 59, 0);
      Shape1.addBox(0F, 0F, 0F, 1, 5, 1);
      Shape1.setRotationPoint(-4F, 11F, -3F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      head3 = new ModelRenderer(this, 33, 8);
      head3.addBox(0F, 0F, 0F, 6, 6, 2);
      head3.setRotationPoint(-3F, -15F, 3F);
      head3.setTextureSize(64, 32);
      head3.mirror = true;
      setRotation(head3, -0.2443461F, 0F, 0F);
      head4 = new ModelRenderer(this, 33, 0);
      head4.addBox(0F, -1F, -3F, 6, 1, 6);
      head4.setRotationPoint(-3F, -15.5F, -1F);
      head4.setTextureSize(64, 32);
      head4.mirror = true;
      setRotation(head4, 0.1396263F, 0F, 0F);
      eyes = new ModelRenderer(this, 0, 17);
      eyes.addBox(0F, 0F, 0F, 6, 1, 1);
      eyes.setRotationPoint(-3F, -13F, -5F);
      eyes.setTextureSize(64, 32);
      eyes.mirror = true;
      setRotation(eyes, 0.1396263F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape9.render(f5);
    rightarm.render(f5);
    Shape8.render(f5);
    rightarm2.render(f5);
    Shape7.render(f5);
    leftarm.render(f5);
    Shape6.render(f5);
    leftarm2.render(f5);
    Shape5.render(f5);
    body.render(f5);
    Shape4.render(f5);
    body2.render(f5);
    Shape3.render(f5);
    head.render(f5);
    Shape2.render(f5);
    head2.render(f5);
    Shape1.render(f5);
    head3.render(f5);
    head4.render(f5);
    eyes.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,entity);
  }

}
