// Date: 21/07/2016 19:04:26
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package elementicraft.client;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLiving;

public class model_elem_test extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer righthand;
    ModelRenderer cube_bac;
    ModelRenderer Shape2;
  
  public model_elem_test()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 8, 7, 7);
      head.setRotationPoint(0F, 0.5333334F, 0F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0.2974289F, 0F, 0F);
      body = new ModelRenderer(this, 0, 18);
      body.addBox(-4F, 0F, -2F, 8, 10, 4);
      body.setRotationPoint(0F, 0F, 0F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 24, 19);
      rightarm.addBox(-3F, -2F, -2F, 4, 9, 4);
      rightarm.setRotationPoint(-5F, 2F, 0F);
      rightarm.setTextureSize(64, 32);
      rightarm.mirror = true;
      setRotation(rightarm, -0.1115358F, 0F, 0.4461433F);
      leftarm = new ModelRenderer(this, 40, 19);
      leftarm.addBox(-1F, -2F, -2F, 4, 9, 4);
      leftarm.setRotationPoint(5F, 2F, 0F);
      leftarm.setTextureSize(64, 32);
      leftarm.mirror = true;
      setRotation(leftarm, -0.2602503F, 0F, -0.4833219F);
      righthand = new ModelRenderer(this, 30, 0);
      righthand.addBox(-4F, -1F, -1F, 4, 5, 4);
      righthand.setRotationPoint(-6F, 7F, -2F);
      righthand.setTextureSize(64, 32);
      righthand.mirror = true;
      setRotation(righthand, -0.5205006F, -0.0743572F, 0.1858931F);
      righthand = new ModelRenderer(this, 30, 9);
      righthand.addBox(-1F, -1F, -3F, 4, 5, 4);
      righthand.setRotationPoint(8F, 8F, -1F);
      righthand.setTextureSize(64, 32);
      righthand.mirror = true;
      setRotation(righthand, -0.5774045F, 0.0371786F, -0.2974289F);
      cube_bac = new ModelRenderer(this, 0, 14);
      cube_bac.addBox(-2.733333F, 0F, -2F, 2, 2, 2);
      cube_bac.setRotationPoint(-7.733333F, -8.866667F, -5F);
      cube_bac.setTextureSize(64, 32);
      cube_bac.mirror = true;
      setRotation(cube_bac, 0.2230717F, 0.2602503F, 0.669215F);
      Shape2 = new ModelRenderer(this, 46, 6);
      Shape2.addBox(-1.866667F, -1.733333F, -1.4F, 3, 3, 3);
      Shape2.setRotationPoint(-2.066667F, 14.2F, 0F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0.7519374F, 0.7435722F, 0.7063936F);
      Shape2 = new ModelRenderer(this, 46, 0);
      Shape2.addBox(-1.6F, -2.066667F, -1.4F, 3, 3, 3);
      Shape2.setRotationPoint(2.133333F, 17.26667F, -0.8F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, -0.5121354F, -0.4833219F, -0.7481163F);
      
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity,f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
   
    
	GL11.glPushMatrix();  
	GL11.glEnable(GL11.GL_NORMALIZE);  
	GL11.glEnable(GL11.GL_BLEND);  
	GL11.glBlendFunc(GL11.GL_SRC_ALPHA, GL11.GL_ONE_MINUS_SRC_ALPHA);    
	GL11.glColor4f(1F, 1F, 1F, 0.75F);    
	//ICI LES PARTIES DU CORPS A RENDRE TRANSPARENTE ex: (    head.render(f5); body.render(f5); ...   )  
    head.render(f5);
    body.render(f5);
    rightarm.render(f5);
    leftarm.render(f5);
    righthand.render(f5);
    cube_bac.render(f5);
    Shape2.render(f5);
	GL11.glDisable(GL11.GL_BLEND);  
	GL11.glPopMatrix();
    
    
    

  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,entity);
  }

}
